dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - 12
before_install:
  - npm i -g npm@6.14.4
install:
  - npm ci
cache:
  yarn: true
script:
  - yarn test
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL