// SPDX-License-Identifier: GPL v3

pragma solidity ^0.8.0;

/**
 * @title RocketpoolEncoder
 * @notice Provides utility functions for generating identifiers in Rocketpool.
 */
library RocketpoolEncoder {
    /**
     * @notice Generates a bytes32 identifier for a contract name.
     * @param contractName The name of the contract.
     * @return The generated bytes32 identifier.
     */
    function generateBytes32Identifier(string memory contractName) internal pure returns (bytes32) {
        return keccak256(abi.encodePacked('contract.address', contractName));
    }
}
